API_BASE_URL = 'https://api.binance.com'
MARKET_DATA_SPOT_API_PREFIX = '/api/v3'
AUTH_HEADER = 'X-MBX-APIKEY'

SYMBOL_BITCOIN = 'BTC'
SYMBOL_ETHEREUM = 'ETH'
SYMBOL_BINANCE = 'BNB'
SYMBOL_RIPPLE = 'XRP'
SYMBOL_DOGE = 'DOGE'
SYMBOL_CARDANO = 'ADA'
SYMBOL_POLKADOT = 'DOT'
SYMBOL_UNISWAP = 'UNI'
SYMBOL_BITCOINCASH = 'BCH'
SYMBOL_LITECOIN = 'LTC'
SYMBOL_CHAINLINK = 'LINK'
SYMBOL_VECHAIN = 'VET'
SYMBOL_SOLANA = 'SOL'
SYMBOL_STELLAR = 'XLM'
SYMBOL_THETA = 'THETA'
SYMBOL_FILECOIN = 'FIL'
SYMBOL_TRON = 'TRX'
SYMBOL_NEO = 'NEO'
SYMBOL_MONERO = 'XMR'
SYMBOL_TERRA = 'LUNA'
SYMBOL_PANCAKESWAP = 'CAKE'
SYMBOL_EOS = 'EOS'
SYMBOL_MIOTA = 'IOTA'
SYMBOL_1INCH = '1INCH'
SYMBOL_HOLO = 'HOT'
SYMBOL_CHILIZ = 'CHZ'
SYMBOL_SWIPE = 'SXP'
SYMBOL_ALIENWORLDS = 'TLM'
SYMBOL_ETHEREUMCLASSIC = 'ETC'

SYMBOL_EURO = 'EUR'
SYMBOL_TETHER = 'USDT'

FROM_SYMBOLS = [
    SYMBOL_CARDANO,
    SYMBOL_BITCOIN,
    SYMBOL_ETHEREUM,
    SYMBOL_LITECOIN,
    SYMBOL_BINANCE,
    SYMBOL_DOGE,
    SYMBOL_RIPPLE,
    SYMBOL_POLKADOT,
    SYMBOL_UNISWAP,
    SYMBOL_BITCOINCASH,
    SYMBOL_LITECOIN,
    SYMBOL_CHAINLINK,
    SYMBOL_VECHAIN,
    SYMBOL_SOLANA,
    SYMBOL_STELLAR,
    SYMBOL_THETA,
    SYMBOL_FILECOIN,
    SYMBOL_TRON,
    SYMBOL_NEO,
    SYMBOL_MONERO,
    SYMBOL_TERRA,
    SYMBOL_PANCAKESWAP,
    SYMBOL_EOS,
    SYMBOL_MIOTA,
    SYMBOL_1INCH,
    SYMBOL_HOLO,
    SYMBOL_CHILIZ,
    SYMBOL_SWIPE,
    SYMBOL_ALIENWORLDS,
    SYMBOL_ETHEREUMCLASSIC,
]
TO_SYMBOLS = [SYMBOL_TETHER]

TRADING_SYMBOLS = [
    f'{f}{t}'
    for f in FROM_SYMBOLS
    for t in TO_SYMBOLS
]

INTERVALS = [
    '1m',
    '3m',
    '5m',
    '15m',
    '30m',
    '1h',
    '2h',
    '4h',
    '6h',
    '8h',
    '12h',
    '1d',
]

MONGO_COLLS = {
    symbol: {i: f'{symbol}_{i}' for i in INTERVALS}
    for symbol in TRADING_SYMBOLS
}
MONGO_COLL_BACKTESTING = 'backtesting'

COMMAND_CRAWL = 'crawl'
COMMAND_CHARTS = 'charts'
COMMAND_TRADE = 'trade'
COMMAND_FILL = 'fill'
COMMAND_FILL_ALL = 'fill_all'
COMMAND_BACKTESTING = 'backtesting'

CRAWLING_SECONDS_WINDOW = 60

MAPPING_KLINES = [
    'timestamp',
    'open',
    'high',
    'low',
    'close',
    'volume',
    'timestamp_close',
    'volume_quote',
    'trades_count',
    'volume_taker_base',
    'volume_taker_quote',
]
KLINE_FIELDS = {'open': 1, 'high': 1, 'low': 1, 'close': 1, 'volume': 1}

DATE_ARG_FORMAT = '%Y%m%d'
DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%f'
DATE_MILIS_PRODUCT = 1000

BACKTESTING_STRAT_IND_SEPARATOR = '-'
BACKTESTING_STRAT_PREFIX = 's'
BACKTESTING_IND_PREFIX = 'i'
