API_BASE_URL = 'https://api.binance.com/'
MARKET_DATA_SPOT_API_PREFIX = '/api/v3'
AUTH_HEADER = 'X-MBX-APIKEY'

SYMBOL_CARDANO = 'ADA'
SYMBOL_BITCOIN = 'BTC'
SYMBOL_ETHEREUM = 'ETH'
SYMBOL_EURO = 'EUR'
SYMBOL_TETHER = 'USDT'
SYMBOL_CARDANO_EURO = f'{SYMBOL_CARDANO}{SYMBOL_EURO}'
SYMBOL_BITCOIN_EURO = f'{SYMBOL_BITCOIN}{SYMBOL_EURO}'
SYMBOL_ETHEREUM_EURO = f'{SYMBOL_ETHEREUM}{SYMBOL_EURO}'
SYMBOL_CARDANO_TETHER = f'{SYMBOL_CARDANO}{SYMBOL_TETHER}'
SYMBOL_BITCOIN_TETHER = f'{SYMBOL_BITCOIN}{SYMBOL_TETHER}'
SYMBOL_ETHEREUM_TETHER = f'{SYMBOL_ETHEREUM}{SYMBOL_TETHER}'

INTERVALS = {
    'second': 'S',
    'minute': 'M',
    'hour': 'H',
    'day': 'D',
}
